//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follower
    {
        public int id_follower { get; set; }
        public Nullable<int> id_followedUser { get; set; }
        public Nullable<int> id_subscriber { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
