//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public int id_tweet { get; set; }
        public Nullable<int> id_user { get; set; }
        public string Tweet1 { get; set; }
    
        public virtual User User { get; set; }
    }
}
