//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Followers = new HashSet<Follower>();
            this.Followers1 = new HashSet<Follower>();
            this.Tweets = new HashSet<Tweet>();
        }
    
        public int id_user { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Follower> Followers { get; set; }
        public virtual ICollection<Follower> Followers1 { get; set; }
        public virtual ICollection<Tweet> Tweets { get; set; }
    }
}
